// Pixel art for every joker, god card, and boss blind. Each sprite is a 12×12
// character grid rendered by PixelSprite; palette chars live in BASE_PALETTE
// (sprites.tsx) with per-sprite overrides. '.' is transparent. Every motif is
// chosen to telegraph the effect: flame = streak, coins = economy, etc.

import type { SpriteDef } from './palette'

// --------------------------------------------------------------------- jokers

export const JOKER_ART: Record<string, SpriteDef> = {
  'jolly-roger': {
    // white skull, classic +mult workhorse
    grid: [
      '...WWWWWW...',
      '..WWWWWWWW..',
      '.WWWWWWWWWW.',
      '.WWWWWWWWWW.',
      '.WKKWWWWKKW.',
      '.WKKWWWWKKW.',
      '.WWWWKKWWWW.',
      '..WWWWWWWW..',
      '..WKWKKWKW..',
      '...WWWWWW...',
      '.ss......ss.',
      'ss..........',
    ],
  },
  'chip-stack': {
    // a stack of poker chips
    grid: [
      '............',
      '..BWBWBWBB..',
      '.BBBBBBBBBB.',
      '..bbbbbbbb..',
      '..WBWBWBWW..',
      '.WWWWWWWWWW.',
      '..wwwwwwww..',
      '..RWRWRWRR..',
      '.RRRRRRRRRR.',
      '..rrrrrrrr..',
      '.KKKKKKKKKK.',
      '............',
    ],
  },
  'red-rally': {
    // waving red banner
    grid: [
      '..s.........',
      '..sRRRRRRR..',
      '..sRRRRRRRR.',
      '..sRRYYRRRR.',
      '..sRRYYRRR..',
      '..sRRRRRRR..',
      '..sRRRRRR...',
      '..sRRRRR....',
      '..s.........',
      '..s.........',
      '..s.........',
      '.sss........',
    ],
  },
  nightshade: {
    // deadly black-purple berries
    grid: [
      '.....EE.....',
      '....EEEE....',
      '.....ee.....',
      '....PPPP....',
      '..PPPPPPPP..',
      '.PPPKPPKPPP.',
      '.PPPPPPPPPP.',
      '.pPPPPPPPPp.',
      '..pPPPPPPp..',
      '...pppppp...',
      '....pppp....',
      '............',
    ],
  },
  'court-favor': {
    // royal crown, face-card patron
    grid: [
      '............',
      '.G...GG...G.',
      '.GG..GG..GG.',
      '.GGG.GG.GGG.',
      '.GGGGGGGGGG.',
      '.GGGGGGGGGG.',
      '.GRGGBGGERG.',
      '.GGGGGGGGGG.',
      '.gggggggggg.',
      '.GGGGGGGGGG.',
      '............',
      '............',
    ],
  },
  'low-roller': {
    // low dice: a 2 and a 3
    grid: [
      '............',
      '.WWWWWW.....',
      '.WKWWWW.....',
      '.WWWWWW.....',
      '.WWWWKW.....',
      '.WWWWWW.....',
      '.wwwwww.....',
      '.....WWWWWW.',
      '.....WKWWWW.',
      '.....WWKWWW.',
      '.....WWWWKW.',
      '.....wwwwww.',
    ],
  },
  digger: {
    // shovel mid-dig
    grid: [
      '......oo....',
      '.....oo.....',
      '.....oo.....',
      '....oo......',
      '....oo......',
      '...oo.......',
      '..SSSS......',
      '.SSSSSS.....',
      '.SSSSSS.....',
      '.sSSSSs.....',
      '..ssss......',
      'oooo...ooo..',
    ],
  },
  minimalist: {
    // one clean empty column
    grid: [
      '............',
      '.WWWWWWWWWW.',
      '.W........W.',
      '.W........W.',
      '.W........W.',
      '.W...CC...W.',
      '.W...CC...W.',
      '.W........W.',
      '.W........W.',
      '.W........W.',
      '.WWWWWWWWWW.',
      '............',
    ],
  },
  'golden-joker': {
    // the classic jester, cast in gold
    grid: [
      '.G........G.',
      '.GG..GG..GG.',
      '..GG.GG.GG..',
      '..GGGGGGGG..',
      '...GGGGGG...',
      '...FFFFFF...',
      '...FKFFKF...',
      '...FFFFFF...',
      '...FFKKFF...',
      '....FFFF....',
      '..GGGGGGGG..',
      '.G.G....G.G.',
    ],
  },
  prospector: {
    // panning for gold
    grid: [
      '............',
      '............',
      '.....G......',
      '...G...G....',
      '............',
      '..ssssssss..',
      '.sSSSSSSSSs.',
      '.sSGSGSGSSs.',
      '..sSSSSSSs..',
      '...ssssss...',
      '............',
      '............',
    ],
  },
  'spade-work': {
    // one big working spade
    grid: [
      '.....SS.....',
      '....SSSS....',
      '...SSSSSS...',
      '..SSSSSSSS..',
      '.SSSSSSSSSS.',
      '.SSSSSSSSSS.',
      '.SSS.SS.SSS.',
      '.....SS.....',
      '....SSSS....',
      '...ssssss...',
      '............',
      '............',
    ],
    palette: { S: '#c8d4ee', s: '#8a97b8' },
  },
  'heart-throb': {
    // a heart with a shine
    grid: [
      '............',
      '..RR....RR..',
      '.RRRR..RRRR.',
      '.RWRRRRRRRR.',
      '.RWRRRRRRRR.',
      '.RRRRRRRRRR.',
      '..RRRRRRRR..',
      '...RRRRRR...',
      '....RRRR....',
      '.....RR.....',
      '............',
      '............',
    ],
  },
  'even-steven': {
    // balanced scales
    grid: [
      '.....GG.....',
      '.GGGGGGGGGG.',
      '.G...GG...G.',
      '.G...GG...G.',
      'GGG..GG..GGG',
      'G.G..GG..G.G',
      'GGG..GG..GGG',
      '.....GG.....',
      '.....GG.....',
      '....GGGG....',
      '...GGGGGG...',
      '............',
    ],
  },
  'odd-couple': {
    // domino: one and three
    grid: [
      '...WWWWWW...',
      '...WWWWWW...',
      '...WWKWWW...',
      '...WWWWWW...',
      '...wwwwww...',
      '...KKKKKK...',
      '...WWWWWW...',
      '...WKWWWW...',
      '...WWWKWW...',
      '...WKWWWW...',
      '...WWWWWW...',
      '...wwwwww...',
    ],
  },
  'quick-draw': {
    // cards fanned fast
    grid: [
      '..CC........',
      '.CC..WWWW...',
      'CC..WWWWW...',
      '....WWWWWW..',
      '.CC.WWRWWW..',
      '..CCWWWWWWW.',
      '....WWWWWWW.',
      '.CC.wWWKWWW.',
      '..C..WWWWWW.',
      '......WWWWw.',
      '.......wwww.',
      '............',
    ],
  },
  sommelier: {
    // a glass for every foundation
    grid: [
      '.CCCCCCCCCC.',
      '.CRRRRRRRRC.',
      '.CRRRRRRRRC.',
      '..CRRRRRRC..',
      '...CRRRRC...',
      '....CCCC....',
      '.....CC.....',
      '.....CC.....',
      '.....CC.....',
      '....CCCC....',
      '..CCCCCCCC..',
      '............',
    ],
  },
  scavenger: {
    // crow with a coin
    grid: [
      '....KKKK....',
      '...KKKKKK...',
      '..KKWKKKKK..',
      '..KKKKKKKK..',
      '.GGKKKKKKK..',
      '.GG.KKKKKKK.',
      '....KKKKKKK.',
      '....KKKKKK..',
      '.....KKKK...',
      '.....KK.K...',
      '.....K..K...',
      '............',
    ],
  },
  streaker: {
    // the streak flame
    grid: [
      '.....R......',
      '....RR......',
      '....RRR.....',
      '...RRRR..R..',
      '...RORRR.RR.',
      '..RROORRRRR.',
      '..ROOYORRRR.',
      '.RROYYYORRR.',
      '.ROYYYYYORR.',
      '.ROYYYYYOR..',
      '..OYYYYYO...',
      '...OOOOO....',
    ],
  },
  momentum: {
    // rocket at full speed
    grid: [
      '.....WW.....',
      '....WWWW....',
      '....WWWW....',
      '....WBBW....',
      '....WBBW....',
      '....WWWW....',
      '...SWWWWS...',
      '..SSWWWWSS..',
      '..S.OOOO.S..',
      '....OYYO....',
      '.....YY.....',
      '.....Y......',
    ],
  },
  'third-time': {
    // every third shines
    grid: [
      '............',
      '.Y.....Y....',
      'YYY...YYY...',
      '.Y.....Y....',
      '............',
      '.....GG.....',
      '....GGGG....',
      '..GGGGGGGG..',
      '...GGGGGG...',
      '....GGGG....',
      '...GG..GG...',
      '............',
    ],
  },
  'deep-cut': {
    // dagger from the waste
    grid: [
      '.....CC.....',
      '.....CC.....',
      '.....CC.....',
      '.....CC.....',
      '.....CC.....',
      '....gGGg....',
      '..ggGGGGgg..',
      '.....SS.....',
      '.....SS.....',
      '.....SS.....',
      '.....SS.....',
      '......s.....',
    ],
    palette: { C: '#c8d4ee' },
  },
  wastrel: {
    // coins out of the bin
    grid: [
      '.....G......',
      '...G....G...',
      '............',
      '.SSSSSSSSSS.',
      '..ssssssss..',
      '..SSSSSSSS..',
      '..SSKSSKSS..',
      '..SSKSSKSS..',
      '..SSKSSKSS..',
      '..SSSSSSSS..',
      '...ssssss...',
      '............',
    ],
  },
  excavator: {
    // pickaxe for empty columns
    grid: [
      '..SSSSSSS...',
      '.SSSSSSSSSS.',
      '.SSS..ooSSS.',
      '.SS..oo..SS.',
      '.S..oo....S.',
      '....oo......',
      '...oo.......',
      '...oo.......',
      '..oo........',
      '..oo........',
      '.oo.........',
      '............',
    ],
  },
  closer: {
    // the door at play twenty
    grid: [
      '.oooooooooo.',
      '.oOOOOOOOOo.',
      '.oOOOOOOOOo.',
      '.oOOOOOOOOo.',
      '.oOOOOOGOOo.',
      '.oOOOOOGOOo.',
      '.oOOOOOOOOo.',
      '.oOOOOOOOOo.',
      '.oOOOOOOOOo.',
      '.oOOOOOOOOo.',
      '.oooooooooo.',
      '............',
    ],
  },
  snowball: {
    // it only grows
    grid: [
      '............',
      '............',
      '....WWWW....',
      '..WWWWWWWW..',
      '.WWWWWWWWWW.',
      '.WWWCWWWWWW.',
      '.WWWWWWWCWW.',
      '.WCWWWWWWWW.',
      '..WWWWCWWW..',
      '....WWWW....',
      '.cc......cc.',
      'cc........cc',
    ],
  },
  'ace-pilot': {
    // aviator wings, ace high
    grid: [
      '............',
      'GG........GG',
      'GGG..WW..GGG',
      '.GGG.WW.GGG.',
      '.GGGWWWWGGG.',
      '..GGWKKWGG..',
      '..GGWWWWGG..',
      '...GWKKWG...',
      '...GWWWWG...',
      '....W..W....',
      '............',
      '............',
    ],
  },
  'gold-tooth': {
    // that grin pays
    grid: [
      '............',
      '.rrrrrrrrrr.',
      'rrRRRRRRRRrr',
      'rRRRRRRRRRRr',
      'rRWWWWWWWWRr',
      'rRWWGWWWWWRr',
      'rRWWWWWWWWRr',
      'rRRRRRRRRRRr',
      'rrRRRRRRRRrr',
      '.rrrrrrrrrr.',
      '............',
      '............',
    ],
  },
  'high-society': {
    // top hat and monocle
    grid: [
      '...KKKKKK...',
      '...KKKKKK...',
      '...KKKKKK...',
      '...GGGGGG...',
      '.KKKKKKKKKK.',
      '............',
      '......CCCC..',
      '......C..C..',
      '......CCCC..',
      '........C...',
      '.........C..',
      '............',
    ],
  },
  undertaker: {
    // discards, buried with honors
    grid: [
      '............',
      '...SSSSSS...',
      '..SSSSSSSS..',
      '..SSSKKSSS..',
      '..SSSKKSSS..',
      '..SSKKKKSS..',
      '..SSSKKSSS..',
      '..SSSKKSSS..',
      '..SSSSSSSS..',
      '..SSSSSSSS..',
      '.EEEEEEEEEE.',
      'EEEEEEEEEEEE',
    ],
  },
  purist: {
    // untouched, pristine
    grid: [
      '.....WW.....',
      '....WWWW....',
      '....WWWW....',
      '...WWWWWW...',
      '...WWWWWW...',
      '..WWWWWWWW..',
      '..WWCWWWWW..',
      '.WWWCWWWWWW.',
      '.WWWWWWWWWW.',
      '..WWWWWWWW..',
      '...WWWWWW...',
      '....WWWW....',
    ],
  },
  'twin-flame': {
    // two flames, one rank
    grid: [
      '.....O..O...',
      '..O..OO.OO..',
      '..OO.OY.YO..',
      '..OY.OY.YO..',
      '..OY........',
      '.WWWW..WWWW.',
      '.WWWW..WWWW.',
      '.WWWW..WWWW.',
      '.WWWW..WWWW.',
      '.WWWW..WWWW.',
      '.wwww..wwww.',
      '............',
    ],
  },
  librarian: {
    // the ledger of reveals
    grid: [
      '............',
      '.oo......oo.',
      '.oWWWooWWWo.',
      '.oWWWWoWWWo.',
      '.oWsWWoWsWo.',
      '.oWWWWoWWWo.',
      '.oWsWWoWsWo.',
      '.oWWWWoWWWo.',
      '.oWWWWoWWWo.',
      '.ooooooooo..',
      '............',
      '............',
    ],
  },
  metronome: {
    // tick... tick... ×3
    grid: [
      '............',
      '....oooo....',
      '....oooS....',
      '...oooSSo...',
      '...ooSSoo...',
      '...oSSooo...',
      '..oSSooooo..',
      '..oGSoooo0..',
      '..ooooooooo.',
      '.oooooooooo.',
      '.oooooooooo.',
      '............',
    ],
    palette: { '0': '#b25a1d' },
  },
  midas: {
    // everything he touches
    grid: [
      '............',
      '.....GGG....',
      '..GGGGGGGG..',
      '.GGGGGGGGGG.',
      '.....GGG....',
      '.....GGG....',
      '...WWGGGWW..',
      '..WWWGGGWWW.',
      '..WWGGGGGWW.',
      '..WGGGGGGGW.',
      '..GGGGGGGGG.',
      '............',
    ],
  },
  phantom: {
    // stacks right through color
    grid: [
      '....WWWW....',
      '..WWWWWWWW..',
      '.WWWWWWWWWW.',
      '.WWKKWWKKWW.',
      '.WWKKWWKKWW.',
      '.WWWWWWWWWW.',
      '.WWWWKKWWWW.',
      '.WWWWWWWWWW.',
      '.WWWWWWWWWW.',
      '.WW.WWW.WWW.',
      '.W...W...W..',
      '............',
      ],
  },
  'kings-gambit': {
    // the king piece
    grid: [
      '.....GG.....',
      '...GGGGGG...',
      '.....GG.....',
      '....WWWW....',
      '...WWWWWW...',
      '....WWWW....',
      '.....WW.....',
      '....WWWW....',
      '...WWWWWW...',
      '..WWWWWWWW..',
      '.wwwwwwwwww.',
      '............',
    ],
  },
  'eleventh-hour': {
    // hands at eleven
    grid: [
      '....WWWW....',
      '..WWWWWWWW..',
      '.WWWWKWWWWW.',
      '.WWWWKWWWWW.',
      'WWWWKKWWWWWW',
      'WWWKKKWWWWWW',
      'WWWWKKKKWWWW',
      '.WWWWWWWKWW.',
      '.WWWWWWWWWW.',
      '..WWWWWWWW..',
      '....WWWW....',
      '............',
    ],
  },
  alchemist: {
    // enhancements, distilled twice
    grid: [
      '....CKKC....',
      '.....CC.....',
      '.....CC.....',
      '.....CC.....',
      '....CCCC....',
      '...CCECCC...',
      '..CCEEECCC..',
      '..CEEEEEEC..',
      '.CEEEYEEEEC.',
      '.CEEEEEEYEC.',
      '..CEEEEEEC..',
      '...CCCCCC...',
    ],
  },
  moneybags: {
    // +1 mult per $10
    grid: [
      '....o..o....',
      '.....oo.....',
      '....oooo....',
      '...oooooo...',
      '..oooooooo..',
      '.oooGGGGooo.',
      '.ooGoooooo..',
      '.oooGGGooo..',
      '.oooooGooo..',
      '.ooGGGGooo..',
      '..oooooooo..',
      '...oooooo...',
    ],
  },
  cliffhanger: {
    // holding on at empty stock
    grid: [
      'SSSS........',
      'SSSS........',
      'SSSSF.F.F...',
      'SSSSFFFFF...',
      'SSSSFFFFFF..',
      'SSSS.FFFF...',
      'SSSS........',
      'SSSS........',
      'SSSS........',
      'SSSS........',
      'SSSS........',
      'SSSS........',
    ],
  },
  philosopher: {
    // the stone rewards the enhanced
    grid: [
      '.....P......',
      '..P.....P...',
      '............',
      '....RRRR....',
      '...RRRRRR...',
      '..RRWRRRRR..',
      '..RRRRRRRR..',
      '..RRRRRRRR..',
      '...RRRRRR...',
      '....RRRR....',
      '..P......P..',
      '.....P......',
    ],
  },
  jackpot: {
    // triple sevens
    grid: [
      '.KKKKKKKKKK.',
      '.KWWWWWWWWK.',
      '.KWRRWRRWRK.',
      '.KW.RW.RW.K.',
      '.KW.RW.RW.K.',
      '.KWWWWWWWWK.',
      '.KKKKKKKKKK.',
      '.KGGGGGGGGK.',
      '.KKKKKKKKKK.',
      '....KKKK....',
      '...KKKKKK...',
      '............',
    ],
  },
  'grand-architect': {
    // drafting the empty board
    grid: [
      '.....GG.....',
      '.....GG.....',
      '....GGGG....',
      '....G..G....',
      '...GG..GG...',
      '...G....G...',
      '..GG....GG..',
      '..G......G..',
      '.BBBBBBBBBB.',
      '.BWBWBWBWBB.',
      '.BBBBBBBBBB.',
      '............',
    ],
  },
  ouroboros: {
    // the streak that never ends
    grid: [
      '...EEEEEE...',
      '..EEEEEEEE..',
      '.EEe....eEE.',
      '.EE......EE.',
      '.EE......EE.',
      '.EE......EE.',
      '.EE......EE.',
      '.EEG.....EE.',
      '..EEE...EEE.',
      '...EEEEEEE..',
      '.....EEEE...',
      '............',
    ],
  },
  pantheon: {
    // every level, one temple
    grid: [
      '.....WW.....',
      '...WWWWWW...',
      '.WWWWWWWWWW.',
      'WWWWWWWWWWWW',
      '.wwwwwwwwww.',
      '.WW.WW.WW.W.',
      '.WW.WW.WW.W.',
      '.WW.WW.WW.W.',
      '.WW.WW.WW.W.',
      '.wwwwwwwwww.',
      'WWWWWWWWWWWW',
      '............',
    ],
  },
  atlas: {
    // carrying the whole round
    grid: [
      '...BBBBBB...',
      '..BEBBBBEB..',
      '.BBBEBBBBBB.',
      '.BBBBBBEBBB.',
      '..BBEBBBBB..',
      '...BBBBBB...',
      '..F.FFFF.F..',
      '..FFFFFFFF..',
      '...FFFFFF...',
      '....FFFF....',
      '....F..F....',
      '....F..F....',
    ],
  },
}

// ---------------------------------------------------------------------- gods

export const GOD_ART: Record<string, SpriteDef> = {
  ares: {
    // sword and shield
    grid: [
      '.....WW.....',
      '.....WW.....',
      '.....WW.....',
      '.....WW.....',
      '...GGWWGG...',
      '.....WW.....',
      '..RRRRRRRR..',
      '..RRRGGRRR..',
      '..RRGGGGRR..',
      '..RRRGGRRR..',
      '...RRRRRR...',
      '....RRRR....',
    ],
    palette: { W: '#dfe6f5' },
  },
  hermes: {
    // the winged sandal
    grid: [
      '............',
      'CC..........',
      'CCC.........',
      '.CCC........',
      'CCCC........',
      '.CC.WWWWW...',
      '....WWWWWW..',
      '....WWWWWWW.',
      '...WWWWWWWW.',
      '...wwwwwwww.',
      '............',
      '............',
    ],
  },
  hestia: {
    // the hearth, always lit
    grid: [
      '.....OO.....',
      '....OOOO....',
      '...OOYYOO...',
      '...OYYYYO...',
      '..OYYYYYYO..',
      '..OYYYYYYO..',
      '...OYYYYO...',
      '....OOOO....',
      '.rrrrrrrrrr.',
      '.rRRrrRRrrr.',
      '.rrrRRrrRRr.',
      '.rRRrrRRrrr.',
    ],
  },
  chronos: {
    // sand still to fall
    grid: [
      '.GGGGGGGGGG.',
      '..GWWWWWWG..',
      '..GWwwwwWG..',
      '..GWwwwwWG..',
      '...GWwwWG...',
      '....GwwG....',
      '....GwwG....',
      '...GW..WG...',
      '..GW.ww.WG..',
      '..GWwwwwWG..',
      '..GwwwwwwG..',
      '.GGGGGGGGGG.',
    ],
  },
  hades: {
    // lord of the burned pile
    grid: [
      '.P........P.',
      '.PP......PP.',
      '.PPP....PPP.',
      '.....PP.....',
      '....PPPP....',
      '...PWWWWP...',
      '...PWKWKP...',
      '...PWWWWP...',
      '....PWWP....',
      '.....PP.....',
      '.....PP.....',
      '.....PP.....',
    ],
  },
  poseidon: {
    // trident over waves
    grid: [
      '.G...GG...G.',
      '.G...GG...G.',
      '.GG..GG..GG.',
      '..GGGGGGGG..',
      '.....GG.....',
      '.....GG.....',
      '.....GG.....',
      '.....GG.....',
      'BB..BB..BB..',
      'BBBBBBBBBBBB',
      '..BB..BB..BB',
      'BBBBBBBBBBBB',
    ],
  },
  zeus: {
    // the bolt of olympus
    grid: [
      '......YYYY..',
      '.....YYYY...',
      '....YYYY....',
      '...YYYY.....',
      '..YYYYYYYY..',
      '.....YYYY...',
      '....YYYY....',
      '...YYYY.....',
      '..YYYY......',
      '..YYY.......',
      '..YY........',
      '..Y.........',
    ],
    palette: { Y: '#ffd93d' },
  },
  apollo: {
    // radiant sun
    grid: [
      '.....GG.....',
      '.G...GG...G.',
      '..G.GGGG.G..',
      '...GGYYGG...',
      '..GYYYYYYG..',
      'GGGYYYYYYGGG',
      'GGGYYYYYYGGG',
      '..GYYYYYYG..',
      '...GGYYGG...',
      '..G.GGGG.G..',
      '.G...GG...G.',
      '.....GG.....',
    ],
  },
  aphrodite: {
    // born of the shell
    grid: [
      '...R....R...',
      '..RRR..RRR..',
      '..RRRRRRRR..',
      '...RRRRRR...',
      '....RRRR....',
      '.....RR.....',
      '.F.F.FF.F.F.',
      '.FFFFFFFFFF.',
      '..FFFFFFFF..',
      '..FFFFFFFF..',
      '...FFFFFF...',
      '....FFFF....',
    ],
    palette: { F: '#ffb8c8' },
  },
  athena: {
    // the owl sees the line
    grid: [
      '.oo......oo.',
      '.ooo....ooo.',
      '.oooooooooo.',
      '.oCCooooCCo.',
      '.oCKCooCKCo.',
      '.oCCooooCCo.',
      '.ooooGGoooo.',
      '.oooooooooo.',
      '..oooooooo..',
      '..oo.oo.oo..',
      '...o..o..o..',
      '............',
    ],
  },
  dionysus: {
    // the grapes decide
    grid: [
      '.....EE.....',
      '....EEEE....',
      '.....ee.....',
      '....PPPP....',
      '..PPPPPPPP..',
      '.PPPPPPPPPP.',
      '.PPPPPPPPPP.',
      '..PPPPPPPP..',
      '..PPPPPPPP..',
      '...PPPPPP...',
      '....PPPP....',
      '.....PP.....',
    ],
  },
  artemis: {
    // moonlit hunt
    grid: [
      '....WWWW....',
      '...WWW......',
      '..WWW.......',
      '..WW....s...',
      '.WWW...sss..',
      '.WWW..sssss.',
      '.WWW...sss..',
      '..WW....s...',
      '..WWW.......',
      '...WWW......',
      '....WWWW....',
      '............',
    ],
    palette: { W: '#dfe6f5', s: '#ffd93d' },
  },
  hecate: {
    // the key to the crossroads
    grid: [
      '....PPPP....',
      '...PP..PP...',
      '...PP..PP...',
      '....PPPP....',
      '.....PP.....',
      '.....PP.....',
      '.....PP.....',
      '.....PPPP...',
      '.....PP.....',
      '.....PPPP...',
      '.....PP.....',
      '............',
    ],
    palette: { P: '#d9a8ff' },
  },
}

// --------------------------------------------------------------------- bosses

export const BOSS_ART: Record<string, SpriteDef> = {
  'the-wall': {
    grid: [
      'rrrrrrrrrrrr',
      'rRRrRRrRRrRR',
      'rrrrrrrrrrrr',
      'RrRRrRRrRRrR',
      'rrrrrrrrrrrr',
      'rRRrRRrRRrRR',
      'rrrrrrrrrrrr',
      'RrRRrRRrRRrR',
      'rrrrrrrrrrrr',
      'rRRrRRrRRrRR',
      'rrrrrrrrrrrr',
      'RrRRrRRrRRrR',
    ],
    palette: { R: '#7a4a3a', r: '#4d2e24' },
  },
  'the-drought': {
    grid: [
      '.....OO.....',
      '..O..OO..O..',
      '...OOOOOO...',
      '..OOYYYYOO..',
      '..OOYYYYOO..',
      '...OOOOOO...',
      '..O..OO..O..',
      '............',
      'oooooooooooo',
      'oo.ooooo.ooo',
      'ooo.ooo.oooo',
      'oooo.o.ooooo',
    ],
  },
  'the-loop': {
    grid: [
      '...CCCCCC...',
      '..CCCCCCCC..',
      '.CC......CC.',
      '.CC......CC.',
      '.CC.........',
      '.CC.........',
      '.CC......C..',
      '.CC.....CCC.',
      '..CC...CCCCC',
      '...CCCCC.C..',
      '.....CC.....',
      '............',
    ],
  },
  'the-crimson': {
    grid: [
      '.....RR.....',
      '.....RR.....',
      '....RRRR....',
      '....RRRR....',
      '...RRRRRR...',
      '...RRRRRR...',
      '..RRRRRRRR..',
      '..RRWRRRRR..',
      '..RRRRRRRR..',
      '...RRRRRR...',
      '....RRRR....',
      '.....RR.....',
    ],
  },
  'the-court': {
    grid: [
      'R...........',
      '.R.......R..',
      '.GR..GG.R.G.',
      '.GGR.GGR.GG.',
      '.GGGRGRGGGG.',
      '.GGGGRGGGGG.',
      '.GGGRGRGGGG.',
      '.GGRGGGRGGG.',
      '.gRggggggRg.',
      '.RGGGGGGGGR.',
      'R..........R',
      '............',
    ],
  },
  'the-weight': {
    grid: [
      '....SSSS....',
      '...SS..SS...',
      '...SS..SS...',
      '..SSSSSSSS..',
      '.SSSSSSSSSS.',
      '.SSSSSSSSSS.',
      '.SSSSSSSSSS.',
      '.SSS22SSSSS.',
      '.SSSSSSSSSS.',
      '..SSSSSSSS..',
      '...ssssss...',
      '............',
    ],
    palette: { S: '#6a7390', s: '#454c63', '2': '#f7f3e8' },
  },
  'the-flood': {
    grid: [
      '............',
      'BB...BB...BB',
      'BBB.BBBB.BBB',
      '.BBBB..BBB..',
      '............',
      'bb...bb...bb',
      'bbb.bbbb.bbb',
      '.bbbb..bbb..',
      '............',
      'BB...BB...BB',
      'BBB.BBBB.BBB',
      '.BBBB..BBB..',
    ],
  },
  'the-toll': {
    grid: [
      '....GGGG....',
      '...GGGGGG...',
      '...GGyGGG...',
      '...GGyGGG...',
      '...GGGGGG...',
      '....GGGG....',
      '............',
      '.KKKKKKKKKK.',
      '.KKKK..KKKK.',
      '.KKKKKKKKKK.',
      '.KKKKKKKKKK.',
      '............',
    ],
    palette: { y: '#fff3c4' },
  },
  'the-silence': {
    grid: [
      'R....GG.....',
      '.R..GGGG....',
      '..R.GGGG....',
      '...RGGGG....',
      '..GGRGGGG...',
      '..GGGRGGG...',
      '..GGGGRGG...',
      '.GGGGGGRGG..',
      'GGGGGGGGRG..',
      '.....GG..R..',
      '....GGGG..R.',
      '............',
    ],
  },
  'the-veil': {
    grid: [
      'P.P.P.P.P.P.',
      '.P.P.P.P.P.P',
      'P.P.P.P.P.P.',
      '............',
      '...WWWWWW...',
      '..WWWWWWWW..',
      '.WWWKKKWWWW.',
      '.WWWKKKWWWW.',
      '..WWWWWWWW..',
      '...WWWWWW...',
      '............',
      '............',
    ],
    palette: { P: '#7e3fb2' },
  },
  'the-hex': {
    grid: [
      '.....PP.....',
      '....PPPP....',
      '...PP..PP...',
      '..PP....PP..',
      '.PPPPPPPPPP.',
      '.PPPPPPPPPP.',
      '..PP....PP..',
      '..PP....PP..',
      '.PP..PP..PP.',
      '.PP.PPPP.PP.',
      '....PPPP....',
      '.....PP.....',
    ],
  },
  'the-fog': {
    grid: [
      '............',
      '.MMMMMM.....',
      'MMMMMMMMMM..',
      '..MMMMMMMMM.',
      '............',
      '....MMMMMMMM',
      '.MMMMMMMMM..',
      'MMMM..MMMMM.',
      '............',
      '..MMMMMMM...',
      '.MMMMMMMMMM.',
      'MMM....MMMM.',
    ],
  },
  'the-anchor': {
    grid: [
      '.....SS.....',
      '....S..S....',
      '....S..S....',
      '.....SS.....',
      '...SSSSSS...',
      '.....SS.....',
      '.....SS.....',
      '.S...SS...S.',
      '.SS..SS..SS.',
      '..SS.SS.SS..',
      '...SSSSSS...',
      '.....SS.....',
    ],
    palette: { S: '#8a97b8' },
  },
  'the-famine': {
    grid: [
      '.....o......',
      '..o..o..o...',
      '.ooo.o.ooo..',
      '..o..o..o...',
      '.....o......',
      '..o..o..o...',
      '.ooo.o.ooo..',
      '..o..o..o...',
      '.....o......',
      '.....o......',
      '....oo......',
      '...oo.......',
    ],
    palette: { o: '#8a6a2a' },
  },
  'the-tithe-boss': {
    grid: [
      '....GGGG....',
      '...GGGGGG...',
      '...GGgGGG...',
      '...GGGGGG...',
      '....GGGG....',
      '..F.F.F.F...',
      '..FFFFFFF...',
      '..FFFFFFFF..',
      '...FFFFFFF..',
      '...FFFFFF...',
      '....FFFF....',
      '....FFFF....',
    ],
  },
  'the-house': {
    grid: [
      '.....KK.....',
      '...KKKKKK...',
      '.KKKKKKKKKK.',
      'KKKKKKKKKKKK',
      '.KKWWKKWWKK.',
      '.KKWWKKWWKK.',
      '.KKKKKKKKKK.',
      '.KKKKGGKKKK.',
      '.KKKKGGKKKK.',
      '.KKWWKKWWKK.',
      '.KKWWKKWWKK.',
      '.KKKKKKKKKK.',
    ],
    palette: { K: '#2a2233', W: '#ffd93d' },
  },
  'the-reaper': {
    grid: [
      '..SSSSSSSS..',
      '.SSSSSSSSSS.',
      '.SS......SSS',
      '.........SS.',
      '......KKSS..',
      '.....KKKK...',
      '....KKKKK...',
      '....KKKKK...',
      '....KKKKK...',
      '....KKKKK...',
      '....KK.KK...',
      '....KK.KK...',
    ],
    palette: { S: '#c8d4ee' },
  },
  'the-eclipse': {
    grid: [
      '.....GG.....',
      '..GGGGGGGG..',
      '.GGKKKKKKGG.',
      '.GKKKKKKKKG.',
      'GGKKKKKKKKGG',
      'GGKKKKKKKKGG',
      'GGKKKKKKKKGG',
      'GGKKKKKKKKGG',
      '.GKKKKKKKKG.',
      '.GGKKKKKKGG.',
      '..GGGGGGGG..',
      '.....GG.....',
    ],
  },
}

// ------------------------------------------------------------------- vouchers

export const VOUCHER_ART: Record<string, SpriteDef> = {
  crowbar: {
    // pry another discard loose
    grid: [
      '..RR........',
      '.RRRR.......',
      '.RR.RR......',
      '.....RR.....',
      '.....RRR....',
      '......RRR...',
      '.......RRR..',
      '........RRR.',
      '.........RR.',
      '.........RR.',
      '........RRr.',
      '.........r..',
    ],
    palette: { R: '#ff6a77', r: '#b52e3c' },
  },
  'perpetual-motion': {
    // the stock never dies
    grid: [
      '....EEEE....',
      '..EEEEEEEE..',
      '.EEE....EEE.',
      '.EE......EE.',
      'EEE.......E.',
      'E.E.........',
      '.........E.E',
      '.E.......EEE',
      '.EE......EE.',
      '.EEE....EEE.',
      '..EEEEEEEE..',
      '....EEEE....',
    ],
  },
  'grease-fingers': {
    // slick reroll discount
    grid: [
      '....C.......',
      '....CC......',
      '...CCC......',
      '....C.......',
      '............',
      '..F.F.F.F...',
      '..FFFFFFF...',
      '..FFFFFFFF..',
      '...FFFFFFF..',
      '...FFFFFF...',
      '....FFFF....',
      '....FFFF....',
    ],
  },
  'deep-pockets': {
    // interest runs deeper
    grid: [
      '.G..G..G....',
      '.GG.GG.GG...',
      '.G..G..G....',
      'bBBBBBBBBBBb',
      'bB........Bb',
      'bBB......BBb',
      '.bBB....BBb.',
      '.bBBB..BBBb.',
      '..bBBBBBBb..',
      '..bBBBBBBb..',
      '...bBBBBb...',
      '....bbbb....',
    ],
  },
  tithe: {
    // blinds pay tribute
    grid: [
      '.....YY.....',
      '....YGGY....',
      '....GGGG....',
      '.....GG.....',
      '............',
      '..GGGGGGGG..',
      '.GGGGGGGGGG.',
      '..gggggggg..',
      '..GGGGGGGG..',
      '.GGGGGGGGGG.',
      '..gggggggg..',
      '............',
    ],
  },
  expansion: {
    // one more joker slot
    grid: [
      '.NNNN..NNNN.',
      '.N..N..N..N.',
      '.N..N..N..N.',
      '.NNNN..NNNN.',
      '............',
      '.NNNN...GG..',
      '.N..N..GGGG.',
      '.N..N.GGGGGG',
      '.NNNN..GGGG.',
      '........GG..',
      '............',
      '............',
    ],
    palette: { N: '#9aa7c4' },
  },
  satchel: {
    // room for one more god
    grid: [
      '....oooo....',
      '...oo..oo...',
      '...o....o...',
      '..OOOOOOOO..',
      '.OOOOOOOOOO.',
      '.OOOOOOOOOO.',
      '.OOOgGgOOOO.',
      '.OOOgGgOOOO.',
      '.OOOOOOOOOO.',
      '.OOOOOOOOOO.',
      '..oooooooo..',
      '............',
    ],
  },
  'lucky-charm': {
    // four leaves, four choices
    grid: [
      '..EE....EE..',
      '.EEEE..EEEE.',
      '.EEEE..EEEE.',
      '..EEE..EEE..',
      '....EEEE....',
      '..EEE..EEE..',
      '.EEEE..EEEE.',
      '.EEEE..EEEE.',
      '..EE....EE..',
      '.....e......',
      '.....ee.....',
      '......ee....',
    ],
  },
  showcase: {
    // a bigger stage for jokers
    grid: [
      'GGGGGGGGGGGG',
      'G..........G',
      'G....YY....G',
      'G....YY....G',
      'G..YYYYYY..G',
      'G.YYYYYYYY.G',
      'G...YYYY...G',
      'G...YYYY...G',
      'G..YY..YY..G',
      'G..........G',
      'GGGGGGGGGGGG',
      '............',
    ],
  },
  'seal-of-approval': {
    // editions, certified
    grid: [
      '....RRRR....',
      '..RRRRRRRR..',
      '.RRRRRRRRRR.',
      '.RRRWWWWRRR.',
      '.RRWWRRWWRR.',
      '.RRWWRRWWRR.',
      '.RRRWWWWRRR.',
      '.RRRRRRRRRR.',
      '..RRRRRRRR..',
      '...RR..RR...',
      '...rr..rr...',
      '..rr....rr..',
    ],
    palette: { R: '#e0435c', r: '#a02840' },
  },
}

// -------------------------------------------------------------------- decks
// Emblems drawn on each deck's card back (DeckBack supplies the themed frame).

export const DECK_ART: Record<string, SpriteDef> = {
  classic: {
    // the honest spade
    grid: [
      '.....GG.....',
      '....GGGG....',
      '...GGGGGG...',
      '..GGGGGGGG..',
      '.GGGGGGGGGG.',
      '.GGGGGGGGGG.',
      '.GGG.GG.GGG.',
      '.....GG.....',
      '....GGGG....',
      '...gggggg...',
      '............',
      '............',
    ],
  },
  gilded: {
    // a fat gold coin
    grid: [
      '...GGGGGG...',
      '..GGGGGGGG..',
      '.GGyGGGGGGG.',
      '.GGyGGGGGGG.',
      'GGGGGGgGGGGG',
      'GGGGGgGgGGGG',
      'GGGGGgGGGGGG',
      'GGGGGgGgGGGG',
      '.GGGGGgGGGG.',
      '.GGGGGGGGGG.',
      '..GGGGGGGG..',
      '...gggggg...',
    ],
    palette: { y: '#fff3c4' },
  },
  merchant: {
    // the hanging scales of trade
    grid: [
      '.....YY.....',
      '.YYYYYYYYYY.',
      '.Y...YY...Y.',
      '.Y...YY...Y.',
      'YYY..YY..YYY',
      'Y.Y..YY..Y.Y',
      'YYY..YY..YYY',
      '.....YY.....',
      '.....YY.....',
      '....YYYY....',
      '...YYYYYY...',
      '............',
    ],
    palette: { Y: '#ffe066' },
  },
  arcane: {
    // the all-seeing eye
    grid: [
      '............',
      '....PPPP....',
      '..PP....PP..',
      '.P..CCCC..P.',
      'P..CCCCCC..P',
      'P.CCCKKCC..P',
      'P.CCCKKCC..P',
      'P..CCCCCC..P',
      '.P..CCCC..P.',
      '..PP....PP..',
      '....PPPP....',
      '............',
    ],
    palette: { P: '#d9a8ff' },
  },
  serpent: {
    // the coiled streak-keeper
    grid: [
      '...EEEEEE...',
      '..EEEEEEEE..',
      '..EE....EE..',
      '........EE..',
      '...EEEEEE...',
      '..EEEEEE....',
      '..EE........',
      '..EEEEEEEE..',
      '...EEEEEEE..',
      '.........EE.',
      '..G......EE.',
      '..EEEEEEEE..',
    ],
  },
}

// big "?" for undiscovered collection entries
export const MYSTERY_ART: SpriteDef = {
  grid: [
    '...SSSSSS...',
    '..SSSSSSSS..',
    '..SS....SS..',
    '........SS..',
    '.......SSS..',
    '......SSS...',
    '.....SSS....',
    '.....SS.....',
    '............',
    '.....SS.....',
    '.....SS.....',
    '............',
  ],
  palette: { S: '#6a7390' },
}

export function deckArt(id: string): SpriteDef {
  return DECK_ART[id] ?? DEFAULT_ART
}

// ----------------------------------------------------------------- face cards
// Court portraits for J/Q/K. The 'A' garment pixels are recolored per suit
// (red suits get crimson robes, black suits navy) by CardView at render time.

export const FACE_ART: Record<'jack' | 'queen' | 'king', SpriteDef> = {
  jack: {
    grid: [
      '...AAAAA....',
      '..AAAAAAA.Y.',
      '..AAAAAAAY..',
      '...FFFFFF...',
      '...FKFFKF...',
      '...FFFFFF...',
      '...FFKKFF...',
      '....FFFF....',
      '..AAAAAAAA..',
      '.AAAWWWWAAA.',
      '.AAWAAAAWAA.',
      '.AAAWWWWAAA.',
      '..AAAAAAAA..',
      '...AA..AA...',
    ],
  },
  queen: {
    grid: [
      '..G..GG..G..',
      '..GG.GG.GG..',
      '..GGGGGGGG..',
      '..oFFFFFFo..',
      '..oFKFFKFo..',
      '..oFFFFFFo..',
      '..oFFKKFFo..',
      '..ooFFFFoo..',
      '..AAAAAAAA..',
      '.AAAGGGGAAA.',
      '.AAGAAAAGAA.',
      '.AAAGGGGAAA.',
      '..AAAAAAAA..',
      '...AA..AA...',
    ],
  },
  king: {
    grid: [
      '.G...GG...G.',
      '.GG..GG..GG.',
      '.GGGGGGGGGG.',
      '..FFFFFFFF..',
      '..FKFFFFKF..',
      '..FFFFFFFF..',
      '..wFFKKFFw..',
      '..wwFFFFww..',
      '.AAwwwwwwAA.',
      '.AAAGGGGAAA.',
      '.AAGAAAAGAA.',
      '.AAAGGGGAAA.',
      '..AAAAAAAA..',
      '...AA..AA...',
    ],
  },
}

// A friendly fallback so unknown ids never render blank.
export const DEFAULT_ART: SpriteDef = {
  grid: [
    '............',
    '..WWWWWWWW..',
    '.WWWWWWWWWW.',
    '.WWKWWWWKWW.',
    '.WWWWWWWWWW.',
    '.WWWWKKWWWW.',
    '.WWWWWWWWWW.',
    '..WWWWWWWW..',
    '....WWWW....',
    '.....WW.....',
    '............',
    '............',
  ],
}

export function jokerArt(id: string): SpriteDef {
  return JOKER_ART[id] ?? DEFAULT_ART
}

export function godArt(id: string): SpriteDef {
  return GOD_ART[id] ?? DEFAULT_ART
}

export function bossArt(id: string): SpriteDef {
  return BOSS_ART[id] ?? DEFAULT_ART
}

export function voucherArt(id: string): SpriteDef {
  return VOUCHER_ART[id] ?? DEFAULT_ART
}
